on: [push, pull_request]

name: R-CMD-check

jobs:
  R-CMD-check:
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: windows-latest, r: release}
          - {os: macOS-latest, r: release}
          - {os: ubuntu-20.04, r: release}
          - {os: ubuntu-20.04, r: devel, http-user-agent: release}

    runs-on: ${{ matrix.config.os }}
  
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-pandoc@v2

      - name: Install macOS system dependencies
        if: runner.os == 'macOS'
        run: |
          brew install udunits

      - uses: r-lib/actions/setup-r-dependencies@v1
        with:
          extra-packages: rcmdcheck,devtools
          needs: check

      - name: Check
        env:
          _R_CHECK_CRAN_INCOMING_: false
        run: |
          options(crayon.enabled = TRUE)
          rcmdcheck::rcmdcheck(args = c("--no-manual", "--as-cran", "--no-tests"), error_on = "warning", check_dir = "check")
        shell: Rscript {0}

      - name: Test
        run: |
          options(crayon.enabled = TRUE)
          res=devtools::test(reporter="summary")
          df=as.data.frame(res)
          if (sum(df$failed) > 0 || any(df$error)) { q(status=1) }
        shell: Rscript {0}
